const express=require("express")
const jwtval=require("../middlewares/jwtvarification")
const { signup, sentotp, varifyOTP, login, CreateMenuItems, submitStaffForm, ListStaff, DeleteStaff, EditStaff, updateStaff, menuupload, menulist, menuDelete, menuEdit, menuItemget, menuitempatch, } = require("../controllers/commonController")
const router=express.Router()
const {upload}=require('../utility/multer/s3storage')
router.post("/signup",signup)
router.post("/send-otp",sentotp)
router.post("/verifyOtp",varifyOTP)
router.post("/login",login)
router.post("/Createmenu",jwtval,CreateMenuItems)
router.post("/addstaff",jwtval,submitStaffForm)
router.get("/addstaff",jwtval,ListStaff)
router.delete("/deletestaff/:id",jwtval,DeleteStaff)
router.get("/edit_staff/:id",jwtval,EditStaff)
router.patch("/edit_staff/:id",jwtval,updateStaff)
router.post('/menuitemsadd',jwtval,upload.single('image'),menuupload)
router.get('/menuitemsadd',jwtval,menulist)
router.delete("/menuitemsdelete/:id",jwtval,menuDelete)
router.get("/menuitems/:Id",jwtval,menuItemget)
router.patch("/menuitems/:id",jwtval,upload.single('image'),menuitempatch)
module.exports=router
